; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:esp32-poe]
platform = espressif32
board = esp32-poe
framework = espidf

; 4 MB flash — default single-app partition fits in 4 MB
board_upload.flash_size = 4MB

; Serial monitor
monitor_baud = 115200

; Build flags: enable Ethernet driver and set BACnet tunables
build_flags =
    -DCONFIG_ETH_USE_ESP32_EMAC=1
    -DMAX_TSM_TRANSACTIONS=10
